# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
xcodebuild -workspace Example/Charleene.xcworkspace -scheme Charleene-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
#cache: cocoapods
#podfile: Example/Podfile
#before_install:
#gem install cocoapods 
#pod install --project-directory=Example
#install:
#- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
#script:
#- set -o pipefail && xcodebuild test -workspace Example/Charleene.xcworkspace -scheme Charleene-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
#- pod lib lint --quick
